### ISSUE TITLE
Index error..!

### ISSUE THREAD

**Issue by jgyy4775** [yaohungt/GSTEG_CVPR_2019#12]
Traceback (most recent call last):
  File "exp/GSTEG.py", line 25, in <module>
    main()
  File "./main.py", line 55, in main
    s_top1,s_top5,o_top1,o_top5,v_top1,v_top5, sov_top1 = trainer.train(train_loader, base_model, logits_model, criterion, base_optimizer, logits_optimizer, epoch, opt)
  File "./train.py", line 142, in train
    o_prec1, o_prec5, o_prec1_output = accuracy(o_output.data, o_target, topk=(1, 5))
  File "./train.py", line 64, in accuracy
    correct[i, j] = target[j, pred[i, j]] > 0.5
IndexError: index -4573023153420993470 is out of bounds for dimension 0 with size 38

> /home/Gated-Spatio-Temporal-Energy-Graph/train.py(64)accuracy()
-> correct[i, j] = target[j, pred[i, j]] > 0.5
(Pdb) exit

what's the problem?

**Comment by yaohungt** [comment]
It is hard to tell what happens in your case. But an index with value -4573023153420993470 is certainly having some problem. Please try to debug on your own, since this is not a problem I can help.

**Comment by jgyy4775** [comment]
The reason for the "indexError" is that the feature become "nan" in "i3d.py".
Sometimes Mixed_3c, and sometimes Conv3d_2c_3*3.
This problem occurs very randomly.

Is there a cause or solution for this problem?
