### ISSUE TITLE
I got feature 'nan' in i3d.py

### ISSUE THREAD

**Issue by jgyy4775** [yaohungt/GSTEG_CVPR_2019#13]
@yaohungt
The reason for the "indexError" is that the feature become "nan" in "i3d.py".
This problem occurs very randomly.
Sometimes Mixed_3c, and sometimes Conv3d_2c_3*3.

Is there a cause or solution for this problem?

**Comment by yaohungt** [comment]
I never face this problem before. I'm afraid this may be some unknown reasons after upgrading PyTorch/ CUDA/ etc. If you'd like to try, there are a tons of feature normalization trick nowadays can help prevent nan problems.
